version: '3.8'

services:
  zookeeper:
    networks:
     - cse-sust-network
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: debezium-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    networks:
     - cse-sust-network  
    container_name: debezium-kafka
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  connect1:
    networks:
     - cse-sust-network  
    container_name: cse-sust-cluster-1
    image: quay.io/debezium/connect:latest
    depends_on:
      - kafka
      - zookeeper
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: my-connect-cluster
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses

  connect2:
    networks:
     - cse-sust-network  
    container_name: cse-sust-cluster-2
    image: quay.io/debezium/connect:latest
    depends_on:
      - kafka
      - zookeeper
    ports:
      - 8084:8083  # Map to a different port to avoid conflict
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: my-connect-cluster  # Same group ID for clustering
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      
  connect3:
    networks:
     - cse-sust-network  
    container_name: cse-sust-cluster-3
    image: quay.io/debezium/connect:latest
    depends_on:
      - kafka
      - zookeeper
    ports:
      - 8085:8083  # Map to a different port to avoid conflict
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: my-connect-cluster  # Same group ID for clustering
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses

  kafdrop:
    networks:
     - cse-sust-network
    container_name: debezium-kafdrop     
    image: obsidiandynamics/kafdrop:3.27.0
    depends_on:
      - kafka
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9092

  sqlserver:
    networks:
     - cse-sust-network  
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: debezium-sqlserver
    ports:
     - 1433:1433
    volumes:
      - mssqlserver:/data     
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_PID=Standard
     - SA_PASSWORD=Password!
     - MSSQL_AGENT_ENABLED=true

  debezium-ui:
    networks:
     - cse-sust-network    
    container_name: debezium-ui
    image: debezium/debezium-ui:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CONNECT_URIS=http://connect1:8083,http://connect2:8084
    depends_on:
      - connect1  
      - connect2

  prometheus:
    networks:
     - cse-sust-network   
    image: prom/prometheus:latest 
    volumes :
     - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount config file
    ports:
     - "9090:9090"  
    depends_on:
      - kafka
      - connect1  
      - connect2
      - connect3

  grafana:
    networks:
     - cse-sust-network    
    image : grafana/grafana:8.5.5
    ports:
     - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel,grafana-clock-panel  # Optional plugins
      - GF_AUTH_BASIC_ENABLED=false  # Disable basic auth for simplicity (adjust for security)
      - GF_USERS_ALLOW_SIGN_UP=false  # Disable user signup
      - GF_DATASOURCES_DEFAULT_DATASOURCE_NAME=Prometheus
      - GF_DATASOURCES_DEFAULT_DATASOURCE_TYPE=prometheus
      - GF_DATASOURCES_DEFAULT_DATASOURCE_URL=http://prometheus:9090  # Replace with your Prometheus endpoint
    depends_on:
      - kafka
      - connect1  
      - connect2
      - prometheus

volumes:
  mssqlserver: { }

networks:
  cse-sust-network:
    name: cse-sust-network
    driver: bridge